#![cfg(target_arch = "aarch64")]
#![cfg(feature = "rust-tests")]

use quicfuscate::accelerate::random;
use quicfuscate::optimize::telemetry::RNG_AES_CTR_OPS;
use quicfuscate::optimize::{CpuFeature, FeatureDetector};

#[test]
fn random_bytes_secure_uses_aes_ctr_when_available() {
    let detector = FeatureDetector::instance();
    if !detector.has_feature(CpuFeature::AES) || !std::arch::is_aarch64_feature_detected!("aes") {
        // Fallback path: ensure the call still succeeds without touching the counter.
        let base = RNG_AES_CTR_OPS.get();
        let mut buf = [0u8; 32];
        random::random_bytes_secure(&mut buf);
        let after = RNG_AES_CTR_OPS.get();
        assert_eq!(base, after, "AES counter should remain untouched without hardware support");
        return;
    }

    let before = RNG_AES_CTR_OPS.get();
    let mut buf = [0u8; 64];
    random::random_bytes_secure(&mut buf);
    let after = RNG_AES_CTR_OPS.get();
    assert!(after >= before + 64, "expected RNG_AES_CTR_OPS to increase by generated bytes");

    let before_u64 = RNG_AES_CTR_OPS.get();
    let _value = random::random_u64();
    let after_u64 = RNG_AES_CTR_OPS.get();
    assert!(after_u64 >= before_u64 + 8, "expected RNG_AES_CTR_OPS to increase after random_u64");
}
